# Generated by Django 3.2.6 on 2021-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210829_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slu',
            field=models.SlugField(max_length=1000),
        ),
    ]
