# Generated by Django 3.2.6 on 2021-08-29 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_slu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slu',
            new_name='slug',
        ),
    ]
