# Generated by Django 3.2.6 on 2021-09-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_prfile_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='post',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
