# Generated by Django 3.2.6 on 2021-09-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='token',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='Address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
