# Generated by Django 3.2.6 on 2021-09-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('app', '0011_userdata1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata1',
        ),
    ]
