# Generated by Django 3.2.6 on 2021-09-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userdata1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
